name: Build with MPLAB X and XC8
description: This action builds a MPLAB X / XC8 project in a Linux container.
branding:
  icon: package
  color: gray-dark
inputs:
  project:
    description: Project folder location
    required: true
  configurations:
    description: Configurations to build (space separated)
    required: true
    default: default
  pre:
    description: Pre-build shell command
    required: false
    default:
  post:
    description: Post-build shell command
    required: false
    default:
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.project }}
    - ${{ inputs.configurations }}
    - ${{ inputs.pre }}
    - ${{ inputs.post }}